language: elixir
elixir:
    - 1.3.3
otp_release:
    - 19.1
sudo: true
services:
  - postgresql
before_script:
    - nvm install 6.2 && nvm use 6.2
    - npm install yarn --global
    - yarn install
    - mix do ecto.create, ecto.migrate
script: mix test
